### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by falzm** [feedbin/feedbin-link-opener-chrome#1]
Hi

Any chance to see a Firefox port of this extension? That would be great.

**Comment by Zegnat** [comment]
I ported this add-on over to Firefox, note however that I do not usually do add-on development:
- [Initial release: version 0.1](https://github.com/Zegnat/feedbin-link-opener-firefox/releases/tag/v0.1)

**Edit**: I should probably add that it uses the old `shift+v`. This isn’t currently configurable. I will add a README file to my repository later.

**Comment by falzm** [comment]
Works like a charm, thank you!

**Comment by benubois** [comment]
Thanks @Zegnat,

I've updated the [blog post](http://blog.feedbin.com/2015/03/09/link-opener-for-chrome/) to link to your version.
